baseURL: /
languageCode: en-us
title: Chirpy Hire
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [300,500]
  hero:
    # Main hero title
    title: The modern way to hire smart.
    # Hero subtitle (optional)
    subtitle: Streamline your job applicant screening process with text messages.
    # Button text
    buttontext: Try it free!
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from /images/___)
    image: /Chirpy-Demo.gif
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    #- systek
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Sign in
    url: https://app.chirpyhire.com/accounts/sign_in
    button: true
  #sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: Completely Automatic
    subtitle: Simplifying your hiring process never felt so.... simple.
    tiles:
    - title: Sign Up
      icon: icon-phone
      text: We give you a local number to share with applicants.
      url: https://calendly.com/knmurphy/chirpydemo
      buttonText: Get yours today
    - title: Screen
      icon: icon-questions
      text: Create custom screening questions for them to answer.
      url: https://calendly.com/knmurphy/chirpydemo
      buttonText: Get started now
    - title: Hire
      icon: icon-hand-shake
      text: Automatically schedule pre-screened interviews via text.
      url: https://calendly.com/knmurphy/chirpydemo
      buttonText: Try free today
  section2:
    title: Humans prefer to text.
    subtitle: It only makes sense that we would utilize this method of communication when it comes to recruiting qualified people.
    features:
    - title: Texting is the number 1 method of communication for Americans under 50.
      text:
      # Icon (from /images/illustrations/icons/___.svg)
      icon: one
    - title: 5 Billion people have access to sending and recieving text messages.
      text:
      icon: five-billion
    - title: 78% of US consumers say receiving a text message is the fastest way to reach them.
      text:
      icon: seventy-eight
    - title: Smart phone users send and receive 5 times more texts than they do phone calls.
      text:
      icon: five-times
  section3:
    title: Meet Chirpy
    subtitle: Hire better people faster and in an organized way.
    image: illustrations/mockups/chirpy-mockup.png
    buttonText: Talk with our Senior Product Manager
    buttonLink: https://calendly.com/knmurphy/chirpydemo
  #section4:
    #title: Recruiters love Chirpy Hire
    #subtitle: We've helped businesses large and small to streamline discovering their most valuable asset... People.
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: chirpy-logo.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      # Icons are from Font Awesome
    - link: https://instagram.com/chirpyhire
      icon: instagram
    - link: https://facebook.com/chirpyhire
      icon: facebook
    - link: https://linkedin.com/chirpyhire
      icon: linkedin
    bulmalogo: false
    product:
    - text: Discover features
      link: /
    - text: Why choose our product?
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    - text: Request features
      link: /
    docs:
    - text: Get started
      link: /
    - text: User guides
      link: /
    - text: Admin guide
      link: /
    - text: Developers
      link: /
    blogroll:
    - text: Latest news
      link: /
    - text: Tech articles
      link: /
    - text: Video blog
      link: /
